package main

import (
	"fmt"
	"go_lang/collections"
	"go_lang/consts"
	"go_lang/consts/projects"
	"go_lang/deferpanicrecovery"
	"go_lang/flowcontrol"
	"go_lang/functions"
	"go_lang/interfaces"
	"go_lang/lib"
	"go_lang/looping"
	"go_lang/pointers"
	"go_lang/primitives"
	"go_lang/routines"
	"go_lang/space"
	//"go_lang/webgo"
)

func main() {
	fmt.Println("This is Main Function being executed")
	space.SayHello()
	lib.Model1()
	space.Model2()
	primitives.BoolFunction()
	primitives.PlayWithNumbers()
	primitives.Calculation()
	fmt.Println()
	primitives.BitWise()
	fmt.Println()
	primitives.BitShift()
	fmt.Println()
	primitives.FloatingNums()
	fmt.Println()
	primitives.FloatingArithmatic()
	fmt.Println()
	primitives.ComplexNumbers()
	fmt.Println()
	primitives.TextType()
	fmt.Println()
	primitives.RuneGo()
	fmt.Println()
	consts.GoConstants()
	fmt.Println()
	projects.FileSizeConverter()
	fmt.Println()
	projects.AdminAccess()
	fmt.Println()
	collections.GradesArray()
	fmt.Println()
	collections.IdentityMatrix()
	collections.CopyOfArray()
	collections.StackinSlice()
	collections.StackPushPop()
	collections.MapsInGo()
	collections.DoctorStruct()
	collections.StructInheritance()
	flowcontrol.IfElseInGo()
	flowcontrol.NumberGuessWithIF()
	flowcontrol.TestForShortcircuiting()
	flowcontrol.SwitchCaseInGo()
	flowcontrol.TypeSwitchInGo()
	looping.SimpleLoopGo()
	looping.ForWhileLoopGo()
	looping.LabledLoop()
	looping.ForEachLoopGo()
	deferpanicrecovery.DeferInGo()
	//deferpanicrecovery.DeferResourceManager()
	deferpanicrecovery.PanicInGo()
	//webgo.HelloWebGO()
	pointers.PointersInGo()
	functions.Function1()
	functions.FunctionsWithPointers()
	functions.SumOfNumbers()
	functions.PointerCallingFun()
	functions.ErrorHandelInGo()
	functions.FuncAsVariable()
	interfaces.InterfaceInGo()
	routines.GoRoutines()
	collections.SliceInGo()
}
